---
- include: configure.yml
  when: mysql_hardening_enabled | bool
  tags:
    - mysql_hardening

- include: mysql_secure_installation.yml
  when: mysql_hardening_enabled | bool
  tags:
    - mysql_hardening
    - mysql_secure_installation
